# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: sky

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: "Researcher in computer graphics at École de Technologie Supérieure."
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Quoc-Minh Ton-That"

# Site footer
footer:
  copyright:
    notice: '© {year} Quoc-Minh Ton-That.' # This work is licensed under {license}
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
  text: Free SVGs by [BGJar](https://bgjar.com), [Park Jisun on Flaticon](https://www.flaticon.com/free-icons/deadlift)

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
